export const mutationSendMessage = {
  arguments: { content: 'tes', sender: 'tes' },
  identity: null,
  source: null,
  request: { headers: [Object], domainName: null },
  prev: null,
  info: {
    fieldName: 'sendMessage',
    selectionSetList: [],
    selectionSetGraphQL: '',
    parentTypeName: 'Mutation',
    variables: {},
  },
  stash: {},
};

export const queryHello = {
  arguments: {},
  identity: null,
  source: null,
  request: {
    headers: {
      'x-amzn-appsync-is-vpce-request': 'false',
      'x-forwarded-for': '177.46.32.32, 15.158.8.228',
      'accept-encoding': 'gzip',
      'cloudfront-is-tablet-viewer': 'false',
      'cloudfront-viewer-country': 'BR',
      'x-amzn-requestid': '0e0c7084-9b15-4771-9354-b4c86cd68e6c',
      'x-amzn-remote-ip': '177.46.32.32',
      via: '2.0 f39fe2af8db1fa0e050bf0415c4cedf2.cloudfront.net (CloudFront)',
      'x-api-key': 'da2-moksskcb6bapdpmbygrrwoul2e',
      'cloudfront-forwarded-proto': 'https',
      'content-type': 'application/json; charset=UTF-8',
      'x-amzn-trace-id': 'Root=1-66a6f230-1b0fbeec54c3c2a1545c43d0',
      'x-amz-cf-id': 'bhOu2gvCL5lvlZJ5uPv1n-UrYYZTX9MXcBDF-XAQ46rN33_h6HaYWQ==',
      'content-length': '528',
      'x-amz-user-agent': 'aws-amplify/6.0.13 api/1 framework/202',
      'x-forwarded-proto': 'https',
      host: '4hebgtc3hzbjpkrj2onora3xz4.appsync-api.sa-east-1.amazonaws.com',
      'user-agent': 'okhttp/4.9.2',
      'cloudfront-is-desktop-viewer': 'true',
      'cloudfront-is-mobile-viewer': 'false',
      'x-forwarded-port': '443',
      'cloudfront-is-smarttv-viewer': 'false',
      'cloudfront-viewer-asn': '28135',
    },
    domainName: null,
  },
  prev: null,
  info: {
    fieldName: 'hello',
    selectionSetList: [],
    selectionSetGraphQL: '{}',
    parentTypeName: 'Query',
    variables: {},
  },
  stash: {},
};
